name = "smaily-commerce-api"
main = "src/index.js"
compatibility_date = "2026-09-25"

[[d1_databases]]
binding = "DB"
database_name = "smaily-commerce-db"
database_id = "171bdf3e-96c4-405f-89e2-83f63901f811"
